/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abbr: typeof import('./src/components/Abbr.vue')['default']
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppLoader: typeof import('./src/components/common/AppLoader.vue')['default']
    AuthScreen: typeof import('./src/components/AuthScreen.vue')['default']
    Button: typeof import('primevue/button')['default']
    Fireworks: typeof import('./src/components/effects/Fireworks.vue')['default']
    FireworksEffect: typeof import('./src/components/effects/FireworksEffect.vue')['default']
    GameCard: typeof import('./src/components/game/GameCard.vue')['default']
    GameCreate: typeof import('./src/components/game/GameCreate.vue')['default']
    GameDetails: typeof import('./src/components/game/GameDetails.vue')['default']
    GameList: typeof import('./src/components/game/GameList.vue')['default']
    GamePlay: typeof import('./src/components/game/GamePlay.vue')['default']
    H1: typeof import('./src/components/H1.vue')['default']
    H2: typeof import('./src/components/H2.vue')['default']
    MainButton: typeof import('./src/components/MainButton.vue')['default']
    MainPanel: typeof import('./src/components/MainPanel.vue')['default']
    NavBar: typeof import('./src/components/common/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
